Q.1 How to import pandas and check the version?

In [1]:
import pandas as pd

print(pd.__version__)

1.0.4

Q.2 How to create a series from a numpy array?

In [2]:

# importing Pandas & numpy 
import pandas as pd 
import numpy as np 
  
# numpy array 
data = np.array(['l', 'e', 't', 's', 'u','p','g','r','a','d','e']) 
  
# creating series 
s = pd.Series(data) 
print(s)

0     l
1     e
2     t
3     s
4     u
5     p
6     g
7     r
8     a
9     d
10    e
dtype: object

Q.3 How to convert the index of a series into a column of a dataframe?

In [2]:
# Creating the dataframe df 
df = pd.DataFrame({'Roll Number': ['2020Nov11', '2020Nov12', '2020Nov13', '2020Nov14'], 
'Name': ['Jagdeep', 'Mohan', 'Ajit', 'Rohan'], 
'Marks In Percentage': [88, 85, 71, 76], 
'Grade': ['O', 'O', 'A', 'A+'], 
'Subject': ['Python', 'AIML', 'DataScience', 'Linux']}) 

# Printing the dataframe 
df

  Roll Number     Name  Marks In Percentage Grade      Subject
0   2020Nov11  Jagdeep                   88     O       Python
1   2020Nov12    Mohan                   85     O         AIML
2   2020Nov13     Ajit                   71     A  DataScience
3   2020Nov14    Rohan                   76    A+        Linux

Q.4 Write the code to list all the datasets available in seaborn library.
Load the 'mpg' dataset
Note: mpg dataset will be read from seaborn module in the manner sir has already shown(provided in the
materials folder)

In [6]:
# Seaborn for plotting and styling
import seaborn as sb
df = sb.load_dataset('tips')
print(df.head())

Matplotlib is building the font cache; this may take a moment.

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
import seaborn as sb
print(sb.get_dataset_names())

/home/jagdeep/anaconda3/lib/python3.7/site-packages/seaborn/utils.py:384: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 384 of the file /home/jagdeep/anaconda3/lib/python3.7/site-packages/seaborn/utils.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  gh_list = BeautifulSoup(http)

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'exercise', 'flights', 'fmri', 'gammas', 'geyser', 'iris', 'mpg', 'penguins', 'planets', 'tips', 'titanic']

In [9]:
df1 = sb.load_dataset('mpg')
print(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Q.5 Which country origin cars are a part of this dataset?

In [17]:
import pandas as pd 
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
%matplotlib inline 
sns.set(color_codes=True)

df = pd.read_csv("CARS.csv")
df.head(5)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197

In [35]:
print("Car Origin from : ",df["Origin"])

Car Origin from :  0        Asia
1        Asia
2        Asia
3        Asia
4        Asia
        ...
423    Europe
424    Europe
425    Europe
426    Europe
427    Europe
Name: Origin, Length: 428, dtype: object

Q.6 Extract the part of the dataframe which contains cars belonging to 'usa'

In [38]:
for usa in df['Origin']:
    if usa==time2:
    print("USA", usa)

USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA USA
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA USA
USA USA
USA USA
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Europe
USA Europe
USA Europe
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA Europe
USA Europe
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA USA
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Asia
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe
USA Europe